[application]
name = "portfolio"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"
public_dir = "assets"

[web.app]
title = "Sreenand P K | Python Developer & Backend Engineer"
icon = "assets/header.png"
port = 3000

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
